name: Release

on:
  push:

jobs:

  Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get tag
      id: tag
      shell: bash
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install Poetry
      run: |
        python get-poetry.py --preview -y
        $env:Path += ";$env:Userprofile\.poetry\bin"
    - name: Install dependencies
      run: |
        $env:Path += ";$env:Userprofile\.poetry\bin"
        poetry install --no-dev
    - name: Preparing Python executables
      run: |
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/2.7.17/python-2.7.17.windows.tar.xz -O python-2.7.17.tar.xz
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/3.4.4/python-3.4.4.windows.tar.xz -O python-3.4.4.tar.xz
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/3.5.4/python-3.5.4.windows.tar.xz -O python-3.5.4.tar.xz
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/3.6.8/python-3.6.8.windows.tar.xz -O python-3.6.8.tar.xz
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/3.7.5/python-3.7.5.windows.tar.xz -O python-3.7.5.tar.xz
        Invoke-WebRequest https://github.com/sdispater/python-binaries/releases/download/3.8.0/python-3.8.0.windows.tar.xz -O python-3.8.0.tar.xz
        7z x python-2.7.17.tar.xz
        7z x python-3.4.4.tar.xz
        7z x python-3.5.4.tar.xz
        7z x python-3.6.8.tar.xz
        7z x python-3.7.5.tar.xz
        7z x python-3.8.0.tar.xz
        7z x python-2.7.17.tar
        7z x python-3.4.4.tar
        7z x python-3.5.4.tar
        7z x python-3.6.8.tar
        7z x python-3.7.5.tar
        7z x python-3.8.0.tar
    - name: Build specific release
      run: |
        $env:Path += ";$env:Userprofile\.poetry\bin"
        poetry run python sonnet make release --ansi -P "2.7:python-2.7.17\python.exe" -P "3.4:python-3.4.4\python.exe" -P "3.5:python-3.5.4\python.exe" -P "3.6:python-3.6.8\python.exe" -P "3.7:python-3.7.5\python.exe" -P "3.8:python-3.8.0\python.exe"
